### ISSUE TITLE
Wrong Rotation with ARW Files

### ISSUE THREAD

**Issue by kutyla-philipp** [photoview/photoview#1115]
**Describe the bug**
Photos are not rotated properly.
This is happening in mobile and desktop view.

Downloading the Picture in "Large" results in the same Rotation Problem.
Downloading the Picture in "Original" ARW the picture will be rotated properly.

**To Reproduce**
1. Download my Testfile: https://files.catbox.moe/npvybs.ARW
2. Add the file to your directory.
3. Scan.

**Expected behavior**
All photos should be rotated properly accoring to the EXIF data when viewing in the UI, as well as when downloading as a JPEG.

**Screenshots**
See Comment.

**Your environment:**
Feel free to remove and add what you think might be useful.

 - Are you using Docker? [yes]
 - Database [postgres]
 - Browser [chrome, safari, firefox]
 - Version [latest]

**Comment by kutyla-philipp** [comment]
Screenshot didn't attach.
![Screenshot_20241104_083849](https://github.com/user-attachments/assets/9fa478b8-cfa5-484d-9096-787a5b055a06)

**Comment by kkovaletp** [comment]
@kutyla-philipp, thanks for reporting the bug and providing the sample file for testing. I was able to reproduce it on my system and found its root cause and the solution.
In fact it is a corner case of ImageMagick usage, which by default doesn't care about image rotation and needs the `-auto-orient` flag to be explicitly provided.
Details are in the https://github.com/ImageMagick/ImageMagick/issues/5183

I'll prepare the fix.

**Comment by kutyla-philipp** [comment]
@kkovaletp Awesome, Thanks a bunch!
