### ISSUE TITLE
Support multiple database systems (including sqlite)

### ISSUE THREAD

**Issue by Darthagnon** [photoview/photoview#130]
[Filebrowser](https://github.com/filebrowser/filebrowser), another GoLang project that is sortof a Google Drive replacement, [uses Bolt as a built-in database](https://filebrowser.org/cli/filebrowser) and thus doesn't need an external database server. Would it be possible to implement Bolt database support in Photoview, e.g. potentially as a fallback in case of no external database, or as an alternative? 

I don't know a whole lot about databases...  The ones I've tried in the past (MongoDB, PostreSQL) were quite heavy for what I was using them for (data storage backend for other Go projects I was testing), and fairly complex to set up.

- [Original Bolt](https://github.com/boltdb/bolt)
- [Updated fork Bbolt](https://github.com/etcd-io/bbolt)

**Comment by viktorstrate** [comment]
Hi @Darthagnon 

I think a lightweight database option with no configuration would be a great addition to Photoview, though since it uses MySQL it would be very hard to integrate Bolt, since it has a completely different structure.

However I don’t think it will be very difficult to integrate SQLite, which is a MySQL server that saves the the database to a single file, and it doesn’t use any external server.

**Comment by Darthagnon** [comment]
Someone I'm following showed me this project: [xo, a Go tool that sounds like it'd be useful to convert between database types](https://github.com/xo/xo)
The blurb from the page:
```
Command line tool to generate idiomatic Go code for SQL databases supporting PostgreSQL, MySQL, SQLite, Oracle, and Microsoft SQL Server
```

Might be helpful and save some manual programming?
(sorry if it's not, and thank you for considering my suggestions!)

**Comment by viktorstrate** [comment]
Thank you for linking it!
I’ve been having a lot of trouble with database compatibilities, and this looks like it could be a great solution.

Might be good a good adoption for Photoview v2, as it will most likely break compatibility. Along with some other issues that require bigger restructuring of the database eg. #67

**Comment by Darrenmeehan** [comment]
Would there be any interest in using DynamoDB? It's a serverless database from AWS that would be a lot cheaper and securer to operate than most others.

**Comment by viktorstrate** [comment]
@Darrenmeehan I think it would be hard to support, since DynamoDB doesn't use SQL. I haven't used AWS before so I know very little about it though.

Besides that, what would be the benefit of a serverless database, when the rest of the back-end isn't, like the scanner and image processor?

Also since the project is targeting self-hosted servers and NASs, it isn't really a problem to use a traditional database, and it's also often simpler to set up.

But if it can be configured to work with [Gorm](https://gorm.io/), I don't see why we can't support it for the few who would benefit from it.
