### ISSUE TITLE
HEIC and HEVC support

### ISSUE THREAD

**Issue by narensankar0529** [photoview/photoview#147]
Any plans to support these formats for iPhone users?

**Comment by viktorstrate** [comment]
Sure this is probably quite easy to support.
Is it possible for you to send me some samples, for testing?

You can either attach them in a zip in a comment, or if you can send them privately to me at viktorstrate@gmail.com

**Comment by narensankar0529** [comment]
[Archive.zip](https://github.com/viktorstrate/photoview/files/5648681/Archive.zip)

Few samples attached

**Comment by viktorstrate** [comment]
Maybe https://github.com/strukturag/libheif could be used for converting to jpeg

**Comment by narensankar0529** [comment]
Yes that should work.

Thanks!
—————

Naren Sankar

**Comment by BMicraft** [comment]
I think at this point there aren't [any webbrowsers that support heic](https://caniuse.com/?search=heic). Since AVIF is very much competitive on filesize/quality maybe focus on that since [support seems better](https://caniuse.com/?search=avif)? (Also Firefox will most likely [enable AVIF support](https://bugzilla.mozilla.org/show_bug.cgi?id=1682995) in one one the next versions)

For encoders the best option for AVIF is probably [libheif](https://github.com/strukturag/libheif) which supports **both** HEIF and AVIF. There is (was) also [go-avif](https://github.com/Kagami/go-avif) but unfortunately that project seems  pretty abandoned.

**Comment by yllekz** [comment]
I'm a bit confused, I have tons of HEIC files and they are all displaying just fine in Photoview. It is already supported from what I can see.

**Comment by viktorstrate** [comment]
@yllekz I haven't had the chance to look at this yet, thank you for reporting.
I will try to verify this later. 👍

**Comment by viktorstrate** [comment]
@yllekz do you have any HEIC files that you can attach in a comment?
I just tried the samples from https://github.com/photoview/photoview/issues/147#issuecomment-739490275 but Photoview didn't pick them up.

**Comment by yllekz** [comment]
My apologies, I retract my statement, I really thought my HEIC files were there, but after checking this morning, apparently all the ones I'm seeing are actually JPG/PNG/etc. I just got a new phone earlier this year that takes HEIC pictures so what I'm seeing is legacy pre-HEIC photo files from the old phone.

**Comment by viktorstrate** [comment]
No problem :)

**Comment by viktorstrate** [comment]
@McDowell-CSSD thank you for the comment, I will take that into account.

**Comment by viktorstrate** [comment]
Photoview can now read `.heic` images, but it doesn't combine videos and photos in the same way as Apple's live photos do.
I have opened a new issue for this based on @McDowell-CSSD's comment https://github.com/photoview/photoview/issues/147#issuecomment-780013517 at #273
