### ISSUE TITLE
Issue showing pictures on web-browser

### ISSUE THREAD

**Issue by gmanolo** [photoview/photoview#202]
I started today to check this platform as a replacement for GP

I tested the original docker-compose.yml file and edited just to access some example photos which were allocated on the host for the docker container.

All photos are properly scanned, structure's folder is replicated as expected and thumbnails are created in api_cache too. But, I don't know why, when accessing from the browser I cannot see or download any picture (original or small thumbnail). 

![image](https://user-images.githubusercontent.com/18553735/108637412-cf782b00-748a-11eb-946b-fed25386cd19.png)

Maybe it's just me as I'm not expert and probably it's my faul. Whatever,  I considered interesting to all of you to share my facts as it could be someting not checked before and it could help on your project.

I didn't found anything on issues panel regarding about this, which makes me think it didn't happen before...

Thanks!

**Comment by gmanolo** [comment]
I figured out myself how to solve it. Very easy in fact but I didn't consider an a needed to modify this parameter. I didn't change in docker-compose.yml the default URL http://localhost:8000 and because of I was testing over an IP address, everything was working but images didn't show ... once I modified it, I reloaded the docker container and they instantly showed up.

**Comment by newone757** [comment]
I have this same issue but I'm not sure I understand your solution that worked. My URL is set to the IP address of the server I am hosting the PhotoView Docker, the database, and my photo library. What exactly did you change your URL to? I am only trying to access this from inside of my own network.

**Comment by viktorstrate** [comment]
@newone757 you should set `PHOTVIEW_PUBLIC_ENDPOINT` to the url you enter in the browser to acces the site.

**Comment by rafadesu** [comment]
I have this problem too. I've configured:
PHOTOVIEW_API_ENDPOINT
PHOTOVIEW_UI_ENDPOINT
This one:  PHOTOVIEW_PUBLIC_ENDPOINT doesn't seem to exist anymore.

It only happens when I use Safari though. It seems to be working fine with Chrome.
I can see in the network debug tab that the browser is requesting many times this:
data:image/gif;base64,R0lGODlhAQABAPAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==

**Comment by viktorstrate** [comment]
@rafadesu do you think your issue is related to #324?

**Comment by rafadesu** [comment]
Yes thanks! However It seems a combination of problems then.

Enabling Lazy Image Loading fixes the problem in Mac OS Safari and iOS Safari. But also, the problem with the requests data:image/gif.... seems to be because the image is in the database but the thumbnail hasn't been processed yet. So when navigating to Photos tab the latest pictures haven't been processed yet and those are precisely the ones that shows first.

I just added the whole library of pictures and videos in one go and it will probably take a few days to process all the photos and videos. I guess it would be nice if the pictures wouldn't show in the interface at all until they are fully processed (or with a pending banner) but I guess if a scan doesn't take too long then it shouldn't be a big deal.

This photo gallery app is amazing @viktorstrate. Congratulations on such a great work and thanks for sharing.

**Comment by viktorstrate** [comment]
@rafadesu thank you, I'm very happy that you like it :)

> But also, the problem with the requests data:image/gif.... seems to be because the image is in the database but the thumbnail hasn't been processed yet.

One reason why incomplete images are shown is because the database query needed to filter them out would make the request a little slower (not a major issue).
Secondly, I think it can be benefical to see incomplete images as you can still open them in the sidebar to for example download the original image before the thumbnail is generated.

Adding a pending banner would be nice, but it would add some complexity as there is currently no way to distinguish between an image that is currently being processed and an image that failed to be processed.
