### ISSUE TITLE
Feature request: Behavior of the bubble button after media greater than visible count

### ISSUE THREAD

**Issue by kaiiiz** [photoview/photoview#230]
![image](https://user-images.githubusercontent.com/30596812/109541536-e0661380-7afe-11eb-8586-4ec448b86177.png)

**Is your feature request related to a problem? Please describe.**
The current behavior of the bubble button is opening the album. But it's quite annoying if the photos in timeline exist in the middle of the album, so you need to scroll down very very long to see the rest of photos at that date (which are not shown in timeline).

**Describe the solution you'd like**
I think it's nicer to directly expand the rest of the photos, or at least open a album link that filtered the date.

**Additional context**
The album link can put in the right tab (like **Attribute** section or something?).

**Comment by viktorstrate** [comment]
I think directly expanding the rest of the media in that album for that day would be a good solution.
You would still be able to navigate to the album by clicking on the album title.

**Comment by ippocratis** [comment]
A tool like [phockup](https://github.com/ivandokov/phockup) theat organizes a photo\video folder in year\month\day could be a temporary workaround

**Comment by J0n4t4n** [comment]
I just installed PhotoView and it's great so far, but this is the one thing that has been bugging me the most.
I would also like to at least have the +XX button show the images directly in line.

For me it would be even better, if there was no +XX button at all and all of the images are displayed always.
Maybe there could be an option somewhere to switch between having +XX and always showing all of the images in the Timeline.

**Comment by ippocratis** [comment]
> I just installed PhotoView and it's great so far, but this is the one thing that has been bugging me the most.
> I would also like to at least have the +XX button show the images directly in line.
> 
> For me it would be even better, if there was no +XX button at all and all of the images are displayed always.
> Maybe there could be an option somewhere to switch between having +XX and always showing all of the images in the Timeline.

The thing is the way it is implemented it follows Your  folder structure (by design) and gets you to the beginning (the first photo) of the  folder where the photos of that date are.
That makes no sense as a behaviour
It should somehow get you to the first photo of the selected date

**Comment by viktorstrate** [comment]
This is by far the most requested feature atm. and the next feature I will be working on.
The reason why this is how it is right now, is because a proper solution is not easy to implement and I have to figure out how exactly it should work and how that should be implemented (also factoring in other features like #347 in the future). The biggest obstacles being performance and future-proofing.

Eg. if it should show all images for an album at a particular day, then what if you took +10.000 images that day, then the pagination should work on an album level as well, like "load the next 8 days, but only half of the last album" that gets complicated fast.

Another solution would be to completely rewrite how the timeline is fetched (which I think would be fine as I don't particularly like how it works now). Then load the first say 400 images, and then group them on the client side, and it would be easy to load more images later, like "load 400 images after the date of the last image loaded". This would, first of all, greatly simplify the API side, and it would give more freedom, but also more computation, to the UI.
