### ISSUE TITLE
Custom HTML/CSS Snippet

### ISSUE THREAD

**Issue by mntmn** [photoview/photoview#371]
**Is your feature request related to a problem? Please describe.**
I want to use Photoview to share photos with press and the public, and I would like to restyle the (shared) pages a bit to include our logo, font, and display CC licensing information. The indexing and sharing functionality is great already.

**Describe the solution you'd like**
The easiest solution for me would be a plain text field in the admin UI or an env variable pointing to a file with a HTML fragment that is inserted into each page. Here, I could include custom CSS to style the pages appropriately.

**Comment by viktorstrate** [comment]
See related issue for logo + sitename #264.

As styled-components generate random class names to keep them unique, custom CSS that targets any classes would break on each new release. Because of this custom CSS is very limited and error prone.

Instead it might be better to add branding options inspired by how Nextcloud does it<sup>1</sup>.
This ties niceley together with the #264 issue and also when dark mode is implemented custom color theming could be kept in mind to allow for custom color palettes as well. #156 

1: https://nextcloud.com/branding/

**Comment by viktorstrate** [comment]
Let's continue this thread over at #264
