### ISSUE TITLE
Cannot setup Photos folder

### ISSUE THREAD

**Issue by kindlydodo** [photoview/photoview#379]
All i want is to setup photoview, and set my Image Directory to : "/home/user/tmp/testimages". I followed the README.md, but it dont work.

That is what i did:

1. git clone
2. created the docker-compose.yml file and edit the file like described in de comment: add a line at 48:
    - ./photos_path:/photos:ro
    - /home/user/tmp/testimages:/photos:ro
3. sudo docker-compose up -d

Now, i open localhost:8000, add a user, but there are no folders / images under "photos" / "albums"

what am I doing wrong?

additionally:

At the "Initial Setup", on the "initial setup wizard" when i add a username and password: What are the "Photo Phat" input Box for? I expect to add the Path of my Image Directory, so i setup a fresh Docker instance, whithout customize the docker-compose.yml file (like described above), and put my path inside: "/home/user/tmp/testimages"...But, i get an error

**Comment by viktorstrate** [comment]
Make sure you don't have two volume mounts for `/photos` (delete `./photos_path:/photos:ro` but keep `/home/user/tmp/testimages:/photos:ro`.

> and put my path inside: "/home/user/tmp/testimages"...But, i get an error

Because you are using Docker, Photoview does not have direct access to your file system, that's why you added the line under volumes. You should write `/photos` for the root path.

For more info, take a look at Docker bind mounts https://docs.docker.com/storage/bind-mounts/
