### ISSUE TITLE
Timeline Photos View

### ISSUE THREAD

**Issue by vdwees** [photoview/photoview#48]
Hi @viktorstrate,

I am enjoying this project a lot. The emphasis on maintaining the existing album structure is really important to me, and is one of the things that sets this project apart. Nevertheless, I find that exploring my photos in a timeline-style adds a nice alternative way of navigating photos. Currently the Photos page and Albums page are offering quite a bit of overlapping functionality, so I tried loading all my pictures into a single PhotoGallery and the performance was reasonably good (https://github.com/vdwees/photoview/commit/974ea5f629e89268319c32b7931cec3a86995ba5). I could see this looking a bit like Google Photos, with pictures delimited by year. What do you think of this functionality?

**Comment by viktorstrate** [comment]
Thank you!

I think this is a great idea.
I have also thought the current Photos page as being somewhat of a temporary solution, and I like the idea of grouping by date – since it is also ordered by date.

I initially didn't set a limit for how many photos that are shown on the Photos page, thus all photos was shown. And even though the images first load when you scroll to them, the page became super slow because it had to layout thousands of gray boxes on the page. This might be solved by setting a limit and the load more photos when the user scrolls to the bottom.

There could maybe also be some way to jump to a specific date. I imagine if you have thousands of pictures, that it could take a long time to scroll down to older photos. Like the timeline to the right on Google Photos.

**Comment by viktorstrate** [comment]
### Suggestion / inspiration for timeline view

![Home](https://user-images.githubusercontent.com/4233458/100153151-05b20880-2ea4-11eb-87ae-a22ad246036a.png)

**Comment by Marco1097** [comment]
For me would be nice to remove completely the album part and see ALL the photos, only group by date. Maybe let the user decide and offer two different timeline view, one with all the photos and the ohter with the album, like the one you posted here above

**Comment by ClumsyAdmin** [comment]
Agree with exactly what Marco said. Just a simple view of all photos by date with albums taking no effect.

**Comment by viktorstrate** [comment]
@Marco1097 @ClumsyAdmin sure, I guess sometimes you just want to browse all your photos and their location isn't important. One solution might be to add a toogle labeled "Show all media", that will show all photos unfiltered and ordered by date when enabled and the one proposed above when disabled?

**Comment by darrepac** [comment]
> ### Suggestion / inspiration for timeline view
> ![Home](https://user-images.githubusercontent.com/4233458/100153151-05b20880-2ea4-11eb-87ae-a22ad246036a.png)

I may miss something but I do not see the timeline at right inspired by google photos...
Is there an option? or may-be I have to wait the full scan process to finish?

thanks

**Comment by viktorstrate** [comment]
@darrepac I've opened a new issue for this, let's continue the discussion over there #295
