### ISSUE TITLE
config option - for base url / subdir

### ISSUE THREAD

**Issue by kcris** [photoview/photoview#503]
I am selfhosting multiple web apps, all of them offer some config option which allow me to specify the `base url`.
That base url is then used by those apps internally, as a prefix for all their internal urls.

This allows me to use a subdirectory on my webserver, for example I would like to expose photoview under `/photos` folder on my webserver, e.g `https://my.server.com/photos`

@viktorstrate : Is this possible with photoview? If not, could we have such an option? 

ps: I saw this thread https://github.com/photoview/photoview/discussions/392
but did not find a proper solution to this.

thanks

**Comment by viktorstrate** [comment]
This is possible but unfortunately only by building the Docker image yourself. The problem is that the UI is static files, and I don't want to tie it to the API as I want it to be as separate from the client as possible.

But by setting `UI_PUBLIC_URL=/photos` when building the image, that information will be baked into the static UI files.

https://github.com/photoview/photoview/blob/5eb4bf83f3fb923975683a5f1664b2350fcedfdf/Dockerfile#L32

You could do this by cloning the repo and changing the docker-compose file to this:

```diff
services:
  photoview:
-    image: viktorstrate/photoview:2
+    build:
+      context: .
+      args:
+        - UI_PUBLIC_URL=/photos
```
