### ISSUE TITLE
on the image sidebar add link to it's album

### ISSUE THREAD

**Issue by dhananjayraut** [photoview/photoview#549]
**Is your feature request related to a problem? Please describe.**
I don't like seeing album names on timeline and feel like they take too much space so I have hidden them using my browser (using ublock origin element picker mode).  as it has been discussed in #490 this prevents me from opening the album from timeline.

**Describe the solution you'd like**
I would like if we can add the link to the album on the image's sidebar. this way it will not take any space and the functionality will still be there.

_after implementing this we can even remove the album names from timeline._

**Comment by HStep20** [comment]
I think this is the best way to do it. Retains functionality for those who use it, but also makes it more visually appealing to those who use a date based hierarchy of folders for organization. It's the problem I've been trying to solve to make this my main photo app for hosting both personal photos and professional ones. 

The Professional photos are great to have subdivided by albums, since they're organized as is, but synced phone photos are much harder to manage at that scale - especially looking backwards in time and trying to retrofit photos to a new setup.

**Comment by dhananjayraut** [comment]
@viktorstrate if you are working on showing additional information on sidebar (#319 & #554) 
would it be possible to add a link to the album in the sidebar as well?
