### ISSUE TITLE
Timestamp not updating during scan

### ISSUE THREAD

**Issue by AaronPorts** [photoview/photoview#630]
When I manually change the timestamp of a photo and rescan the database, the date_shot field in the media_exif table is not updating.
I guess we should add a check for the valid timestamp data here:
https://github.com/photoview/photoview/blob/e50912451095271261d8ef13274d3a5c8b8e5ab3/api/scanner/scanner_media.go#L93-L107

**Comment by MickMorley** [comment]
Until this is corrected, is there is manual command that we can run to update existing files?

i.e. I am adding coordinates to pictures but since they already exist, the UI is not updating with the new exif attributes.  I validated everything is valid by making a copy of the file. Thus a new photo is added to Photoview with coordinates and is added to Places.

**Comment by Tuxie** [comment]
I suspect this is the same problem that makes it not recognize if an image is replaced with a different image with the same name. Like if I develop an updated version of an image with Darktable/RawTherapee/Lightroom/etc, overwriting the old, it's still the first version in Photoview forever.

**Comment by h4de5** [comment]
i understand having the scanner compare dates all the time, would decrease performance drastically. but maybe an additional option in the scan area could help.

**Comment by kkovaletp** [comment]
This issue is going to be fixed in the scope of the #860 implementation, so closing this one as not planned
