### ISSUE TITLE
Fail to Display .RAF-files

### ISSUE THREAD

**Issue by b3nd1k** [photoview/photoview#647]
Hey! I've a few .RAF-files (Fuji Raw-files) in my library. When scanning my library, Photoview gives out the following error. It won't display the pictures either, instead it shows a black box. 

```
Scanner error
Failed to begin database transaction: failed to process photo (/photos/2020/07/Photo 20-07-23 18-33-16 7675.raf): creating high-res cached image: encoding image using: /usr/bin/darktable-cli [/photos/2020/07/Photo 20-07-23 18-33-16 7675.raf media_cache/42
```

**Comment by viktorstrate** [comment]
Can you provide a sample image that causes the error?

**Comment by b3nd1k** [comment]
Of course, I've looked into it further and the issue seems to be happening with both .DNG-files as well as .RAW-files. I've shared two of the pictures that causes errors here: https://cloud.ddy.no/s/YZCLoocfdHw6n2b

The link is valid for 7 days.

**Comment by viktorstrate** [comment]
I tried opening the samples using the Darktable GUI but I got the following error message.
The images might be supported in newer versions of Darktable, but otherwise the problem lies on Darktable not supporting those particular image formats.

<img width="579" alt="Screenshot 2022-02-13 at 16 43 14" src="https://user-images.githubusercontent.com/4233458/153760923-ecb47acd-691a-41eb-b213-fe1ab468f5de.png">

**Comment by viktorstrate** [comment]
I don't see how it could have anything to do with dark mode either?

Photoview uses [Darktable](https://www.darktable.org/) to process RAW images, if it can't be opened by that, it can't be processed by Photoview. Take a look to see if you can open your images in Darktable, otherwise I'd suggest you open an issue over at that project instead.

**Comment by b3nd1k** [comment]
Oh, all right. I misunderstood. I thought "Darktable" was refering to dark mode. My mistake.

**Comment by viktorstrate** [comment]
Sure no problem ☺️ I'll close this issue then
