### ISSUE TITLE
[Refactoring] Very slow album view for huge photo collection in deep directory trees.

### ISSUE THREAD

**Issue by TheAnachronism** [photoview/photoview#705]
I'm currently trying out this application with a photo/media collection of around 200+ GB. The “special” thing about it is quite organized in very deep directory trees. I don't know if that is the reason, but it's something I though could be important.

The main problem is that loading this entire library into photoview and then wanting to access the album page, it takes around 5-6 seconds or even longer before it displays anything. I thought there might be some error, so I had a look at the logs and found that the SQL Statements were taking so long. Especially this one: `SELECT * FROM `albums` WHERE id IN...`. After the IN keyword there are thousands of IDs listed that as far as I can guess the IDs of the different subdirectories are.
I don't know how one could improve this but I thought it was something that should be known.

Just to show how large this can become:
![image](https://user-images.githubusercontent.com/32616088/174408697-cd330682-d114-42b6-babb-5b23c32a3b8e.png)

**Comment by viktorstrate** [comment]
Thank you for digging into this. Subqueries can be very slow.
The queries used to get the media for the timeline are a little complex so I'm not sure it's possible to rewrite them without using subqueries directly, but maybe it could make sense to simplify the query and then do more post-processing in Go afterwards.

If anyone have experience optimizing SQL queries, help would be much appreciated.

**Comment by TheAnachronism** [comment]
I have no knowledge about your internal structure, but currently it seems like you give all Albums (directories and subdirectories) to the client or at least from the database. Something that might help, but could require a bigger rewrite is, that only the albums/directories that the client should currently see get queried from the database. If the client is in the root directory, he's not interested in the directories that are 5 layers further down.
Of course that would mean, that the database had to be queried more often as a request would be made each time the client switches directories, but I think in this case and application that could be OK.

The decision is just if you want to make fewer but larger/slower queries, or quite a bit more but smaller/faster queries.

**Comment by TheAnachronism** [comment]
After digging a bit in the code, I found the album struct for your database representation:
```go
type Album struct {
	Model
	Title         string `gorm:"not null"`
	ParentAlbumID *int   `gorm:"index"`
	ParentAlbum   *Album `gorm:"constraint:OnDelete:SET NULL;"`
	// OwnerID       int `gorm:"not null"`
	// Owner         User
	Owners   []User `gorm:"many2many:user_albums;constraint:OnDelete:CASCADE;"`
	Path     string `gorm:"not null"`
	PathHash string `gorm:"unique"`
	CoverID  *int
}
```

As I mentioned earlier, something that might help is querying only the albums that have the currently viewed album by the client as their parent album ID. I am not certain how feasible that is to rework, but that could help.

**Comment by kkovaletp** [comment]
I have experience in planning and managing SQL DB performance optimizations in my previous closed-source projects, so here are my thoughts and recommendations, learned from that time:
- Optimize DB architecture in a way, so that the most frequently executed heavy SQL queries do not require many joins and sub-queries
- Use and maintain tables' indexes in the most relevant state according to your queries. Some DBMSs are smart enough to create indexes automatically based on DB execution history (like PostgreSQL), but it is still not enough: a predefined set of indexes, applied as a migration, will noticeably improve performance even if some of them were auto-created
- Use pagination for (potentially) large tables - this will speed the execution of queries up, which know and respect pagination
- Optimize SQL queries to be as simple as possible, query only needed data (avoid querying a lot of data with heavy filtering of the results or using only a subset of returned results). Measure SQL queries' performance and test them in a sandbox with a large dataset, lint them using various SQL optimization advisers or AI
- Use Views to replace the most frequently called heavy queries, left in the app after all previous optimization steps: in this way, we tell DBMS that we're going to read this combination of data regularly, so it can prepare and cache it for us in the background
- Review the next layers of data processing on the backend and move as much functionality as possible from the app code to DB triggers and procedures - the DBMS functionality to run triggers and procedures is much more reliable and provides much better performance compared to the source code of the app

I assume that while you went through these optimization steps, you might have noticed that not everything is supported by all 3 DBMSs, that Photoview currently supports. So, my question is: how important for the project is keeping the support of SQLite - the simplest, slowest DBMS in the list, which doesn't support many mentioned optimizations? If we can pay this price and drop SQLite support to improve the DB performance significantly, then I have the next question: as more optimizations we implement, as more differences are between MariaDB and PostgreSQL (we need to write the same migrations twice, as MySQL and PGSQL are different), so, are we ok with that or we also could drop 1 of them from support to decrease the level of complexity and increase the maintainability of the code? I'd prefer to stay with PostgreSQL, as it is better optimized for performance and large datasets, but we could evaluate pros and cons of each later in this thread.
