### ISSUE TITLE
Selectable Album thumbnail

### ISSUE THREAD

**Issue by FelixUster** [photoview/photoview#89]
Hey,

thank you very much for this project. It is basically what I am looking for. 
It would be great, if it would be possible to select the album thumbnail, instead of using the earliest Picture in a folder. 
of course, I am willing to help, maybe you can hint me to the respective file, as I have never used JS or Go.

**Comment by viktorstrate** [comment]
Hi @FelixUster 

I think this is would be a nice feature.
It could be implemented in a similar way as how Google Photos does it. Clicking a button labeled "Use as album cover".

If you have very little experience with Javascript and Go, then I think it would be quite ambitious to implement this.
But if you want to give it a shot nevertheless, here are the basic steps:

- Add a [database migration](https://github.com/viktorstrate/photoview/tree/master/api/database/migrations) where a new column is added for a potential cover image, referencing the media_id of the selected cover image.
- Add and implement a graphql mutation to change the cover of an album.
- Update the [album thumbnail resolver](https://github.com/viktorstrate/photoview/blob/bbff25973e0017061ab2b5f43562a9e3825e4d9e/api/graphql/resolvers/album.go#L102-L127) to use the selected album cover if set, otherwise use the current implementation to dynamically select the first one.
- Integrate the graphql mutation into the web interface.

**Comment by viktorstrate** [comment]
Implemented in #526

**Comment by jiangzhenjerry** [comment]
Hi! Sorry for bumping a closed ticket. I do enjoy the "Set as album cover photo" function, so thanks for implementing it. On the other hand, maybe one day this feature could be extended a bit? For example, for the following folder structure:

```
Folder A
├── Folder B
│   ├── 1.jpg
│   └── 2.jpg
└── Folder C
    ├── 3.jpg
    └── 4.jpg
```
We can now easily change the cover photos of Folder **B** and Folder **C**, but not that of Folder **A** because Folder A doesn't have any photos directly under it.

Furthermore, if I change the cover photo of Folder **B** to 2.jpg (from 1.jpg by default), Folder **A** would still use 1.jpg (first photo in the first subfolder) as the cover photo. It would be nice if Folder **A** at least follows my choice of cover photo for Folder B.

**Comment by EgonHeuson** [comment]
This would be an amazing feature!! ❤️ But Photoview is already a very nice job! Thanks!!

**Comment by hcooper** [comment]
+1 controlling the album cover of a parent album would be great.

**Comment by Lingxi-Li** [comment]
+1 for the feature to set cover page of albums that contain no photo but only sub-albums.

**Comment by gemini0x2** [comment]
+1 for this feature!

**Comment by J0n1k4** [comment]
Ok. This is the closest topic, and it looks a good place to add my experience.
I have installed Photoview a few days ago, and I am still learning how to properly use it.
I have 2 events that I wanted to share photos with my friends and cousins. My scenario:
Folder "2026" with no pictures, but 2 subfolders.

<img width="616" height="372" alt="Image" src="https://github.com/user-attachments/assets/f9580ce1-ad80-4f20-abea-5b6d54b174a7" />
<img width="1194" height="694" alt="Image" src="https://github.com/user-attachments/assets/e2f2498f-dde5-4de0-aeb6-9a1e81f19c76" />

Subfolder "2026-02-15 - .........." With 13 subfolders and 552 files (of which 4 rather short movies)
Inhere, the first taken picture was 2026-02-15-272.JPG, but I changed the timestamp for some other more appropriate picture and renamed it to 2026-02-15-001.JPG - this was before I found that I can set the album picture.)

<img width="1596" height="769" alt="Image" src="https://github.com/user-attachments/assets/b4db13e6-1e99-47e2-ba5a-fe49f5375372" />

Subfolder "2026-02-21 - .........." With 183 pictures.

I successfully changed the album thumbnail for 2 albums/(sub)folders "2026-02-15 - .........." and "2026-02-21 - ..........", but I can not change the "2026" main folder's Thumbnail - it somewhere stores the info that 2026-02-15-272.JPG was the first picture and uses its thumbnail, even though I have changed the "first" picture by name and by EXIF timestamp in the first album, and multiple times applied "Reset cover photo" (as seen on second screenshot above).

Edit: I have managed to override the "2026" thumbnail problem by copying desired photo in the "2026" folder along 2 subfolders, and from the "info" for that added picture select "Set as album cover photo". Not so elegant - but effective.

Cheers,
N

P.s. - unrelated to this "main album"'s issue - I am not sure why are the AVI movies placed at the beginning when sorted by date, even though their time taken are later than some pictures. 
When sorted by name (title) - their order is correct. Should I open another issue for this as I didn't find any similar issue?
